package homework.day4.odev2.core.mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.8.0
//
// Created by Quasar Development 
//
//----------------------------------------------------

import java.util.Date;


public interface RABDateTimeConverter
{
    Date convertDateTime(String strDate);
    Date convertTime(String strDate);
    Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}